Repository grafeas/voucher, pull requests merged in 2021-12, with the labels that each got.

#48 Separate http and auth token clients
  v2/client/client.go
Labels: size/M

#49 Use idtoken for auth with basic as fallback
  v2/cmd/voucher_client/README.md
  v2/cmd/voucher_client/config.go
  v2/cmd/voucher_client/root.go
Labels: size/S

#50 containeranalysis: close grpcClient
  v2/containeranalysis/client.go
  v2/go.mod
Labels: size/XS

#53 Add support for ADC using voucher_client
  v2/client/client.go
  v2/cmd/voucher_client/README.md
  v2/cmd/voucher_client/config.go
  v2/cmd/voucher_client/defaultclient.go
  v2/cmd/voucher_client/root.go
Labels: size/M

#57 auth.GenerateIdToken
  v2/cmd/voucher_client/defaultclient.go
  v2/go.mod
  v2/go.sum
Labels: size/M

#52 voucher-client: send User-Agent
  v2/client/client.go
  v2/client/client_test.go
  v2/cmd/voucher_client/config.go
Labels: size/M

#54 client: functional opts for constructor
  v2/client/client.go
  v2/client/client_test.go
  v2/client/defaultidtoken.go
  v2/cmd/voucher_client/config.go
Labels: size/L
