Repository grafeas/voucher, pull requests merged in 2021-09, with the labels that each got.

#31 Makefile: v2 module
  .github/workflows/test.yml
  .goreleaser.yml
  Dockerfile
  Makefile
Labels: size/M

#35 secrets: load from sops
  .prettierrc.js
  config/secrets.production.ejson
  testdata/test.ejson
  testdata/test.sops.json
  testdata/test_repo.ejson
  v2/cmd/config/secrets.go
  v2/cmd/config/secrets_test.go
  v2/go.mod
  v2/go.sum
Labels: size/L

#38 Golangci lint actions
  .github/workflows/test.yml
  v2/auth/error.go
  v2/cmd/voucher_subscriber/subscriber.go
  v2/subscriber/subscriber.go
Labels: size/S

#39 golang-1.16
  .github/workflows/test.yml
  Dockerfile
  v2/go.mod
  v2/go.sum
  v2/repository/github/queries_test.go
Labels: size/XS

#37 Datadog direct metrics
  config/config.toml
  config/secrets.production.ejson
  v2/cmd/config/metrics.go
  v2/cmd/config/secrets.go
  v2/cmd/voucher_server/server.go
  v2/cmd/voucher_subscriber/subscriber.go
  v2/go.mod
  v2/go.sum
  v2/metrics/datadog.go
  v2/metrics/datadog_test.go
  v2/metrics/statsd.go
Labels: size/XL

#43 ci: extend linter timeout
  .github/workflows/test.yml
Labels: size/XS

#44 Change Voucher Client server configuration to avoid conflict with environment variables
  v2/cmd/voucher_client/README.md
  v2/cmd/voucher_client/config.go
  v2/cmd/voucher_client/root.go
Labels: size/S
